set_property PACKAGE_PIN U2 [get_ports AN0]
set_property PACKAGE_PIN U4 [get_ports AN1]
set_property PACKAGE_PIN V4 [get_ports AN2]
set_property PACKAGE_PIN W4 [get_ports AN3]
set_property PACKAGE_PIN W7 [get_ports CA]
set_property PACKAGE_PIN W6 [get_ports CB]
set_property PACKAGE_PIN U8 [get_ports CC]
set_property PACKAGE_PIN V8 [get_ports CD]
set_property PACKAGE_PIN U5 [get_ports CE]
set_property PACKAGE_PIN V5 [get_ports CF]
set_property PACKAGE_PIN U7 [get_ports CG]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W16 [get_ports sw2]
set_property PACKAGE_PIN W17 [get_ports sw3]
set_property PACKAGE_PIN W15 [get_ports sw4]
set_property PACKAGE_PIN V15 [get_ports sw5]
set_property PACKAGE_PIN R2 [get_ports sw_clk]
set_property IOSTANDARD LVCMOS33 [get_ports AN1]
set_property IOSTANDARD LVCMOS33 [get_ports AN2]
set_property IOSTANDARD LVCMOS33 [get_ports AN3]
set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports CB]
set_property IOSTANDARD LVCMOS33 [get_ports CC]
set_property IOSTANDARD LVCMOS33 [get_ports CD]
set_property IOSTANDARD LVCMOS33 [get_ports CE]
set_property IOSTANDARD LVCMOS33 [get_ports CF]
set_property IOSTANDARD LVCMOS33 [get_ports CG]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports sw0]
set_property PACKAGE_PIN V16 [get_ports sw1]
set_property PACKAGE_PIN V17 [get_ports sw0]
set_property IOSTANDARD LVCMOS33 [get_ports sw1]
set_property IOSTANDARD LVCMOS33 [get_ports sw2]
set_property IOSTANDARD LVCMOS33 [get_ports sw3]
set_property IOSTANDARD LVCMOS33 [get_ports sw4]
set_property IOSTANDARD LVCMOS33 [get_ports sw5]
set_property IOSTANDARD LVCMOS33 [get_ports sw_clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sw_clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports AN0]



set_property PACKAGE_PIN T18 [get_ports sw_sel]
set_property IOSTANDARD LVCMOS33 [get_ports sw_sel]
